### ISSUE TITLE
Auto change every 24 hours (are you accepting Pull Requests?)

### ISSUE THREAD

**Issue by jimiatnymbl** [pgc062020/DailyDesktopWallpaperPlus_macOS#2]
I've been a Windows user for many years (Linux before that).  Now I'm using a Mac (for work, but thinking about making the switch permanently).  Was happy to find a replacement for MS' Bing Daily wallpaper.  However, it doesn't appear to auto refresh every day.  I had assumed that is what the "Change Desktop Background Automatically" setting would do, but looking at the code I don't see anywhere that does this.

I've created a branch and made a local version for me that updates every 24 hours (if you have Change Desktop Background Automatically set to true).  I can submit a PR if you are interested.

**Comment by pgc062020** [comment]
Hi Jimiatnymbl 

I'm pleased that you found this app!
Since there was no app in exactly this style, I had the idea to develop this app.

Now: 
Since I always shut down the computer at night and restart it the next morning, that was never an issue for me.
That the background image changes automatically within a certain period of time.
I am currently working on an update.
But I don't know when exactly I'll be deploy it. (It's a leisure project ;-) )
I will add an option where the background-picture change automatically after a few hours.

Best regards.

**Comment by pgc062020** [comment]
Hi Jimi

I just uploaded a new release (v2.0) of the DDWP source code on GitHub.
I added your function (automatic wallpaper change).
The time can be changed in the settings window.

Cheers.
